server:
  port: 8080
  servlet:
    context-path: /
 
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/swpu?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    encoding: UTF-8
  resources:
  
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,classpath:/static/images/,classpath:/static/js/,classpath:/static/css/
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.swpu.diet_healthydomain
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    com:
      swpu:
        trace
